spring:
  redis:
    host: redis-1-service
  datasource:
    url: jdbc:mariadb://${prodDbIp}:3306/ghaSample__prod?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: ${prodDbId}
    password: ${prodDbPw}
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
    hibernate:
      ddl-auto: none
  security:
    user:
      name: user
      password: pass
      roles:
        - MEMBER
logging:
  level:
    root: info
    com.ll.exam.ghasample.app: info
    org.hibernate.type.descriptor.sql: info
custom:
  genFileDirPath: /gen
  site:
    baseUrl: "https://site-a.com"